# Generated by Django 5.1.7 on 2025-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('catalog', 'Каталог'), ('price', 'Прайс')], max_length=10, unique=True, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
    ]
